---
owner: LizardByte-bot  # Your GitHub organization or username, where this repository lives
repo: upptime  # The name of this repository

sites:
  - name: website
    url: https://app.lizardbyte.dev
  - name: database
    url: https://db.lizardbyte.dev
  - name: cache
    url: https://app.lizardbyte.dev/uno
  - name: docs
    url: https://docs.lizardbyte.dev
  - name: feedback board
    url: https://feedback.lizardbyte.dev
  - name: ThemerrDB
    url: https://app.lizardbyte.dev/ThemerrDB
#  - name: discord-bot
#    url: $DISCORD_BOT_URL
#  - name: reddit-bot
#    url: $REDDIT_BOT_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lizardbyte.dev
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/LizardByte/.github/master/branding/logos/logo.svg
  name: LizardByte
  introTitle: "**LizardByte** status page"
  introMessage: ''
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
notifications:
  NOTIFICATION_DISCORD: true
  NOTIFICATION_DISCORD_WEBHOOK: true
  NOTIFICATION_DISCORD_WEBHOOK_URL: $DISCORD_WEBHOOK_URL

# https://upptime.js.org/docs/configuration#repository-metadata
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: false
