---
owner: LizardByte-bot  # Your GitHub organization or username, where this repository lives
repo: upptime  # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"  # every day at midnight
  responseTime: "0 23 * * *"  # every day at 11pm
  staticSite: "0 1 * * *"  # every day at 1am
  summary: "0 0 * * *"  # every day at midnight
  updateTemplate: "0 0 * * *"  # every day at midnight
  updates: "0 3 * * *"  # every day at 3am
  uptime: "4/5 * * * *"  # every 5 minutes
  # starting at 0 has issues with queued jobs getting dropped, see: https://stackoverflow.com/a/63192190/11214013

sites:
  - name: Crowdin
    url: https://translate.lizardbyte.dev
  - name: Developer Dashboard
    url: https://app.lizardbyte.dev/dashboard
    __dangerous__body_degraded: 'Traceback (most recent call last):'
  - name: Discord bot
    url: $DISCORD_BOT_URL/status
    icon: >-
      https://cdn.prod.website-files.com/6257adef93867e50d84d30e2/6266bc493fb42d4e27bb8393_847541504914fd33810e70a0ea73177e.ico
    __dangerous__body_degraded: '"status": "degraded"'
  - name: Docs
    url: https://docs.lizardbyte.dev
    icon: https://docs.readthedocs.io/favicon.ico
  - name: GameDB
    url: https://app.lizardbyte.dev/GameDB
  - name: uno
    url: https://app.lizardbyte.dev/uno
  - name: Website
    url: https://app.lizardbyte.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lizardbyte.dev
  # baseUrl: /upptime
  # favicon supports PNG or SVG
  favicon: https://raw.githubusercontent.com/LizardByte/.github/master/branding/logos/logo-32x32.png
  logoUrl: https://raw.githubusercontent.com/LizardByte/.github/master/branding/logos/logo.svg
  name: LizardByte Status
  # intro text
  introTitle: "**LizardByte** status page"
  introMessage: ''
  # custom navbar links
  navbar:
    - title: Help
      href: https://app.lizardbyte.dev/support
    - title: Community
      href: https://github.com/orgs/LizardByte/discussions
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night
  # custom js
  scripts:
    - src: https://cdn.jsdelivr.net/npm/@lizardbyte/shared-web@latest/dist/discord.js
  js: "window.onload = function() { window.initDiscord() }"

# https://upptime.js.org/docs/configuration#repository-metadata
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: false

# https://upptime.js.org/docs/configuration/#skip-delete-issues
skipDeleteIssues: true

# Upptime also supports notifications, assigning issues, and more
# The values need to be added as repository secrets
# See https://upptime.js.org/docs/notifications
